# See /LICENSE for more information.
# This is free software, licensed under the GNU General Public License v2.

include $(TOPDIR)/rules.mk

LUCI_LANG := en zh-cn
LUCI_TITLE:=LuCI HC Service
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all

PKG_LICENSE:=GPL-2.0
PKG_MAINTAINER:=Wuguanghai<wuguanghai45@126.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
